spring:
  application:
    name: billsafe

  datasource:
    url: jdbc:postgresql://${DB_HOST:host.docker.internal}:${DB_PORT:5432}/${DB_NAME:billsafe}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin123}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
  jwt:
    secret: 4jVh5i5GHR7piL6sjcOgjBbI9MqTWKDlmjFJEmXKdN5
    expiration: 86400000
  logging:
    level:
      org.springframework.security: DEBUG

  file:
    upload-dir: uploads

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: yugtank05@gmail.com
    password: zqdizeuysfzugzja
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET}